// config/httpCodes.js

module.exports = {
    // HTTP Status Codes
    STATUS_OK: 200,
    STATUS_NO_CONTENT: 204,
    STATUS_REQUEST_ACCEPTED: 204,
    STATUS_CREATED: 201,
    STATUS_BAD_REQUEST: 400,
    STATUS_UNAUTHORIZED: 401,
    STATUS_FORBIDDEN: 403,
    STATUS_NOT_FOUND: 404,
    STATUS_SERVER_ERROR: 500,
    STATUS_CONFLICT: 409,
};
  